### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by natadnp** [natadnp/homepage#6]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by dasha-korotkykh** [comment]
Хей, привіт! Якщо ти складаєш резюме про себе чи улюбленого персонажа/людину, тобі потрібно написати цей контент самій, я буду рада його продивитися і порадити щось, якщо буде потрібно. Якщо ти складаєш сторінку на замовлення Рю або Дональда, тобі потрібно взяти інформацію з їхніх файлів відповідно, які вказані в описі завдання. Знаєш де лінки на ті файли, чи скинути тобі? :)
P.S. те саме стосується і інших issues

**Comment by natadnp** [comment]
https://www.fb.com/DonaldTrump
    realDonaldTrump@whitehouse.gov
    https://twitter.com/realDonaldTrump
    https://www.instagram.com/realDonaldTrump/
